apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sigulon-campaign-worker
  namespace: sigulon
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sigulon-campaign-worker
